import React from "react";

import Song from "./Song";

//songarr should be [{file: "filename", song: "songname"}]
//PROPS Must include songarr
class Playlist extends React.Component{
  constructor(props){
    super(props);
    this.state = {
      songs: new Array(1)
    }
    this.songRef = React.createRef();
  }
  componentDidMount(){
    var songarr = this.props.songarr;
    var length = songarr.length;
    
      const newsongs = new Array(length);
      //adds song info/wave to the containers after they have been generated by render
      for(let i = 0; i < length; i++){
        var container = document.getElementById("wavesurfer"+i+"wave");
        newsongs[i] =  
        (
        <div>
          
          <div id = {"wavesurfer"+i+"controls"}>
          
            
          <Song file = {songarr[i].file} name = {songarr[i].name}
               container = {"wavesurfer"+i+"wave"} onPlay = {this.playingSong.bind(this)} ref = {this.songRef}/>
            

          </div>
        </div>);
        container.style = "display: 'none'";
      }
      this.setState({songs: newsongs})
  }

  playingSong(s){
    // var toClose = this.songRef.current.filter(function (e) {return e!=s});
    // toClose.forEach(this.songRef.current.closeContainer());
    // toClose.forEach(function (e) {e.state.container.display = "none";});
    // toClose.forEach(function (e) {e.stop()})
  }



  render(){
    var songarr = this.props.songarr;
    var length = songarr.length;
    var divs = new Array(length);
    //renders containers for waveforms
    for(let i = 0; i < length; i++){
      divs[i] = 
      <div class = {"wavesurfer"+i+" block"}>
        <div class = "block">{this.state.songs[i]}</div>
        <div id = {"wavesurfer"+i+"wave"} >
        </div>
      </div>
    }
    return divs;
  }

}
export default Playlist;

